name: deep_animator
channels:
- pytorch
- defaults
dependencies:
- jupyter
- pytorch>=1.3.0
- imageio==2.3.0
- numpy==1.15.0
- matplotlib==2.2.2
- pandas==0.23.4
- Pillow==5.2.0
- scikit-image==0.14.0
- scikit-learn==0.19.2 
- scipy==1.1.0
- pip
- tqdm
- fire
- ffmpeg